#!/bin/bash

EXTRA_EXEC="$*"
tac \
  | awk \
  -v extra_exec="$EXTRA_EXEC" \
  -v branches="$( \
  git branch -v \
  | awk '
    BEGIN {
      out = "";
    }
    {
      if ($1 == "*") {
        branch = $2;
        commit = $3;
      } else {
        branch = $1;
        commit = $2;
      } if (branch !~ /[.]bck[.][0-9]*$/) {
        out = out "," branch ":" commit
      }
    }
    END {
      gsub(/^:/, "", out);
      print(out)
    }'
  )" \
  '
  BEGIN{
    patsplit(branches, a, "[^,:]*:",b);
    first_done = 0;
    for (k in a){
      gsub("[:,]", "", a[k]);
      gsub("[:,]", "", b[k]);
      c[b[k]]=a[k];
      x["pick"]=1;
      x["edit"]=1;
      x["squash"]=1;
      x["drop"]=1;
      x["reword"]=1;
      x["fixup"]=1;
    };
  } {
    if (($1 in x) && ($2 in c)) {
      if (first_done == 1) {
        printf("exec git backup '"'"'%s'"'"' && git branch -f '"'"'%s'"'"' HEAD\n", c[$2], c[$2]);
      } else {
        first_done = 1
      }
      if (extra_exec != "") {
        print("exec", extra_exec);
      }
      print($0);
    } else {
      print($0)
    }
  }' \
  | tac

